name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment package
        run: tar -czf deploy.tar.gz * .github .gitignore

      - name: Copy package to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.tar.gz"
          target: "~/deployment" 

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/cmu-nmu-final-work
            
            cd ~/deployment
            
            tar -xzf deploy.tar.gz -C ~/cmu-nmu-final-work
            
            cd ~/cmu-nmu-final-work
            
            docker compose up --build -d
            
            docker image prune -f