name: Deploy to Server
on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push my-app image
        uses: docker/build-push-action@v4
        with:
          context: ./my-app  
          push: true      
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-final-app:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}         
          username: ${{ secrets.SERVER_USER }}     
          key: ${{ secrets.SSH_PRIVATE_KEY }}      

          script: |

            cd ~/cmu-nmu-final-work || git clone https://github.com/${{ github.repository }}.git ~/cmu-nmu-final-work
            cd ~/cmu-nmu-final-work

            git pull
     
            docker-compose pull
            

            docker-compose up -d
            
            docker image prune -f